### PR TITLE
Mouse drag and drop not working

### PR DESCRIPTION
**Pull request by onemen**
#21

After long time it is finally finished

@117649 can you test it?

### CODE REVIEW

**Comment by 117649** [comment]
@onemen I'll do it. Will let you know if I found anything broken ASAP.

May be consider some announcement to get more ppl involved into testing?

**Comment by 117649** [comment]
@onemen Some times while drag tab from window to window if drop indicator were made display on most left of tab bar of one window but the tab is not drop to that window the indicator stuck on that window.

**Comment by onemen** [comment]
> @onemen Some times while drag tab from window to window if drop indicator were made display on most left of tab bar of one window but the tab is not drop to that window the indicator stuck on that window.

I see the same, it look like that when you leave the window directly to the left dragleave event doesn't fire.
 
> And I'm not feel **When dragging a tab move it directly** doing anything?
> What is it's function?

It is the default behavior for dragging tabs on single row, tabs move directly without drop indicator. if you turn it off you will see  drop indicator also on single row

**Comment by onemen** [comment]
@117649 try it with the latest commit

**Comment by onemen** [comment]
> And I'm not feel **When dragging a tab move it directly** doing anything?
> What is it's function?

   this._moveTabOnDragging = Tabmix.prefs.getBoolPref("moveTabOnDragging");
this should be a getter 

its Interesting that no one ever reported about this bug.
maybe we can drop it

**Comment by 117649** [comment]
> 
> 
> @117649 try it with the latest commit

@onemen Still can stuck indicator under some circumstance. Only seem works on **When dragging a tab move it directly** is false. To reproduce: drag tab to other window to make indicator display then do not release and move mouse back to original window and to where the tab is without cause indicator display on original window. Now the indicator of the other window will stuck on.
图片

**Comment by onemen** [comment]
I will look into it

I can stuck indicator on Firefox without Tabmix.
open 2 tabs or more drag 2nd tab to the left while holding CTRL. exit the window from the left of the tabbar. 
then drop new window will open but the indicator is stuck on the original window
window

**Comment by onemen** [comment]
@117649 
I hope i'v fixed all issues with the last refactor

**Comment by 117649** [comment]
> 
> 
> @117649
> I hope i'v fixed all issues with the last refactor

@onemen I don't see the problem still occur.

**Pull request merged**
