### PR TITLE
join extra spaces and build-in space

### PR DESCRIPTION
**Pull request by 117649**

### CODE REVIEW

**Comment by 117649** [comment]
@onemen Will this work?

**Comment by onemen** [comment]
I will test it tomorrow

**Comment by onemen** [comment]
I don't like this fix, the spacer is left of the buttons if user have buttons on the left, the spacer should be between the button an the tabs.

The current situation before this path, when user hide the to menu and enable our extra space:
- when there are buttons on the toolbar they are between the spaces so user see:
   15x space from up - buttons - 40px from Firefox spacer.
- when user don't have buttons there is one big spacer of 55px.

My suggestion is:
- in case our spacer is visible reduce the size of Firefox spacer to 25px, so the max size is 15+25 = 40
- you don't need to change the css for our spacer

```diff
In tab.js
        Tabmix.setItem(tabBar, "tabBarSpace", Tabmix.prefs.getBoolPref("tabBarSpace") || null);
+       Tabmix.setItem("TabsToolbar", "tabBarSpace", Tabmix.prefs.getBoolPref("tabBarSpace") || null);
```
```diff
In general.css
+     #TabsToolbar[tabBarSpace] .titlebar-spacer[type="pre-tabs"],
+     #TabsToolbar[tabBarSpace] .titlebar-spacer[type="post-tabs"] {
+       width: 25px;
+     }
```

Let me know what you think about this idea ?

**Comment by 117649** [comment]
> Let me know what you think about this idea ?

Working well for me.

**Comment by onemen** [comment]
Thank you.
I will look into it in the morning.

**Pull request merged**
