### PR TITLE
Add proton style to our options window

### PR DESCRIPTION
**Pull request by onemen**
While fixing #58, I'v decided to apply proton style to our options window

The colors and look match Firefox own **Settings** page

@117649, can you check how it look on your PC

### CODE REVIEW

**Comment by 117649** [comment]
图片
图片
The last digit of a max size number input have a slightly cut on its right.
Looks like spinner offset need a increase.

图片
Tabs inside pane a not look so pretty. And hard to understand their function. May be add some background color or border line to better explain what they are.

图片
May be because the color strip are placed invert?

**Comment by onemen** [comment]
> The last digit of a max size number input have a slightly cut on its right.
> Looks like spinner offset need a increase.

input-number

That is how it look in my PC.
Maybe something in your display configuration or font settings is different.
I can increase padding by 1-2px, but since i don't know why we have different input size i'm not sure that we have a UI that works for everyone


> Tabs inside pane a not look so pretty. And hard to understand their function. May be add some background color or border line to better explain what they are.

This is how it look like before
mouse-click

Can you draw on the image where you think different background and/or color strip can help?

**Comment by onemen** [comment]
> Tabs inside pane a not look so pretty. And hard to understand their function. May be add some background color or border line to better explain what they are.

Also if you find web page with tabs that look better post a link

**Comment by 117649** [comment]
> Can you draw on the image where you think different background and/or color strip can help?

Just trying to copy what **about:addons** looks like here. I mean the current style just feel detached from the panel below not make me think it is a click-able object at first glance but some random labels.
图片
图片

**Comment by 117649** [comment]
> Maybe something in your display configuration or font settings is different.

I'm using 1920x1080 and 100% scale a 17" laptop display.
Nothing seem unusual here.

**Comment by onemen** [comment]
new-mouse-click

Is It better ?

**Comment by 117649** [comment]
> 
> 
> new-mouse-click
> 
> Is It better ?

Yes. It may not very proton like but it sure feel better.

**Comment by onemen** [comment]
Check the latest commits.

I think i'm going to enable this design from Firefox 91, regardless if the preference ```browser.proton.enabled``` is set to false.
Firefox already remove most of ```@media (-moz-proton)``` flag from css code.

**Comment by 117649** [comment]
I wasn't notice this early on. These 2 were not in the tab panel before and I think they shouldn't since they are not changing with tab selection.
图片

**Pull request merged**
