### PR TITLE
Load overlay only for selected PrefPane

### PR DESCRIPTION
**Pull request by onemen**
With the code from ```preferences.xml```, when Tabmix options was opened it would only loaded overlay for last selected PrefPan, then on when use switch to different pane it load only the new selected pane

@117649, check this pr an see if you find any issues

### CODE REVIEW

**Comment by 117649** [comment]
Not sure if this is needed any more. There is not a visible different on speed for me.
And I have to say without it make our attempt to fix input width a little bit easier since everything is loaded into view at once.
I also found that dialog expand when switching to a larger pane. May be some css are needed?

Otherwise not found anything broken yet.

**Comment by onemen** [comment]
> I also found that dialog expand when switching to a larger pane. May be some css are needed?

That is by design, that how it work with Firefox xml

**Comment by 117649** [comment]
> 
> 
> > I also found that dialog expand when switching to a larger pane. May be some css are needed?
> 
> That is by design, that how it work with Firefox xml

When it was xul the dialog open at a fixed size regardless last opened pane.

**Comment by onemen** [comment]
> When it was xul the dialog open at a fixed size regardless last opened pane.

Look at ```prefs-ce.js``` the  code that you ported from ```preferences.xml``` , there is ```_shouldAnimate``` getter that sould be off when ```browser.preferences.animateFadeIn``` is off.
Maybe there is a bug ?

**Comment by 117649** [comment]
> 
> 
> > When it was xul the dialog open at a fixed size regardless last opened pane.
> 
> Look at `prefs-ce.js` the code that you ported from `preferences.xml` , there is `_shouldAnimate` getter that sould be off when `browser.preferences.animateFadeIn` is off.
> Maybe there is a bug ?

Maybe `window.sizeToContent()` should also not be called here. `_shouldAnimate` call this too.
https://github.com/onemen/TabMixPlus/blob/ba44679b7acc04d512ad1c68353dde515e5f3a14/addon/chrome/content/preferences/preferences.js#L706

**Comment by onemen** [comment]
> Maybe `window.sizeToContent()` should also not be called here. `_shouldAnimate` call this too.
> 
> https://github.com/onemen/TabMixPlus/blob/ba44679b7acc04d512ad1c68353dde515e5f3a14/addon/chrome/content/preferences/preferences.js#L706

No, line 706 only resize on window load one time, here the code that resize when another higher pane is opens.
this code was copied from Firefox old preferences.xml file
https://github.com/onemen/TabMixPlus/blob/ba44679b7acc04d512ad1c68353dde515e5f3a14/addon/chrome/content/preferences/prefs-ce.js#L1647-L1661

we can eliminate this by setting the height manually to be fixed

**Comment by onemen** [comment]
Actually, I'v remembered that i already set fixed height.

https://github.com/onemen/TabMixPlus/blob/ba44679b7acc04d512ad1c68353dde515e5f3a14/addon/chrome/skin/preferences.css#L228-L231

But since we know have a ```<vbox class="content-box">``` around the content we have to check all css rules that have child combinator (>)  after ```prefpane```

**Comment by 117649** [comment]
> 
> 
> Actually, I'v remembered that i already set fixed height.
> 
> https://github.com/onemen/TabMixPlus/blob/ba44679b7acc04d512ad1c68353dde515e5f3a14/addon/chrome/skin/preferences.css#L228-L231
> 
> But since we now have a `<vbox class="content-box">` around the content we have to check all css rules that have child combinator (>) after `prefpane`

Could it('>') be just removed?

**Pull request merged**
