### PR TITLE
Fix some error caused by adding buttons from overlay

### LINKED ISSUE #30: Append button not create good widgets
I just got Fx86.0b4 dropped.
Then:
`ReferenceError: Windows is not defined Overlays.jsm:755:5`
Shows up and it look like everything else is not load correctly due to it.

### PR DESCRIPTION
**Pull request by 117649**
Trying fix #30

### CODE REVIEW

**Review by onemen — CHANGES_REQUESTED** [review]
Thank you.

1. Please move all new "Windows" code to new file ```windowsUtils.jsm``` or some other proper name place the new file and ChromeManifest.jsm and Overlays.jsm in addon/modules/bootstrap
2. fix all eslint errors and warning, im planing on add some CI action to Github to automatically test for eslint error

**Comment by 117649** [comment]
> Thank you.
> 
> 1. Please move all new "Windows" code to new file `windowsUtils.jsm` or some other proper name place the new file and ChromeManifest.jsm and Overlays.jsm in addon/modules/bootstrap
> 2. fix all eslint errors and warning, im planing on add some CI action to Github to automatically test for eslint error

I don't have eslint...

I just took Windows.jsm from Tab-Group and adding needed and comment out unwanted.

**Comment by onemen** [comment]
> I don't have eslint...

Don't you use [node](https://nodejs.org) at all?

**Comment by 117649** [comment]
> > I don't have eslint...
> 
> Don't you use [node](https://nodejs.org) at all?

No

**Comment by onemen** [comment]
can you add a permission to me to edit the pull request in github

**Comment by 117649** [comment]
> can you add a permission to me to edit the pull request in github

image
This is default to on, anything else need to change?

**Comment by onemen** [comment]
can you rebase your pr with the latest commit from rewrite/main

**Comment by 117649** [comment]
For some reason later commits stayed at the place they are added to the branch...

**Comment by 117649** [comment]
Sorted it out.

**Review by onemen — APPROVED** [review]

**Pull request merged**
