### PR TITLE
Implement Multi-row

### PR DESCRIPTION
**Pull request by onemen**
Fix Multi-row not working #16

Work in progress....

Scrolling with pinned tabs is not perfect

drag & drop on mutli-row will be fixed by #21

### CODE REVIEW

**Comment by 117649** [comment]
And the new tab button would blink many times on it own if select tab that close to ends while use multi-row.

**Comment by 117649** [comment]
However there still a not rare chance to achieve new tab button at row start state.
image
It seems easier to do when closing tabs.

**Comment by 117649** [comment]
image
`tabmix-firstTabInRow` is not be properly assigned but there is a `first-visible-unpinned-tab` we can use.

**Comment by 117649** [comment]
Option of max number of rows to display has no effect.
And dynamic style for not allow pinned tabs to scroll is also not properly applied while browser start. Toggle the check box may be required.

**Comment by 117649** [comment]
Tried compensate on `topTabY`:
```js
get topTabY() {
    return this.scrollClientRect.top +
      Tabmix.getStyle(this.tabBar.arrowScrollbox.scrollbox, "paddingTop") - this.tabBar.arrowScrollbox.scrollPosition;
  },
```
https://github.com/onemen/TabMixPlus/blob/06f6e91b6c0dd39af5854d31755c712472e80ff9/addon/chrome/content/tab/tab.js#L928-L931

Solved most of problem so far.

**Comment by 117649** [comment]
Are we only missing a dynamic rule for max row number here?

**Comment by onemen** [comment]
maybe we can use css variable to set mex-height and set it to max row number time tab height

**Comment by 117649** [comment]
image
Tested use dynamic rule set css variable works.

How can get these changes to you so you can test them?
I may be able to post a pr to this branch but I'm afraid anyway it have to mix in what I changed for #36.

**Comment by onemen** [comment]
> How can I get these changes to you so you can test them?
you can create new testing branch in your repository and post a link here

**Comment by 117649** [comment]
https://github.com/117649/TabMixPlus/commit/a10fdcbd44a18aaa3a3d1e660229d87711b71e6b

**Comment by 117649** [comment]
https://github.com/onemen/TabMixPlus/blob/f0ad97ec06511995677603d0bb2ad3e972eb5aad/addon/chrome/content/overlay/multirow.css#L21
This `!important` here cause tab bar extended over window edge! While not use multi-row!

And this one:
https://github.com/onemen/TabMixPlus/blob/f0ad97ec06511995677603d0bb2ad3e972eb5aad/addon/chrome/content/minit/tablib.js#L419-L423 
a `tab._pinnedUnscrollable = true;` is actually needed here to fix scroll button for multi-bar and un-scrollable pinned tab.
Whit that https://github.com/onemen/TabMixPlus/pull/41#commitcomment-49210197 is not needed.

Final result would be like:
```js
for (let i = 0; i < numPinned; i++) {
 let tab = tabs[i];
 tab.style.setProperty("margin-inline-start", width + "px", "important");
 width += layoutData.pinnedTabWidth;
 tab._pinnedUnscrollable = true;
}
```

And according to this:
https://github.com/mozilla/gecko-dev/blob/5e2e54579b35ce547d21e169e0bb51799af1cbd1/browser/base/content/tabbrowser-tabs.js#L1019-L1021
We may not need to replace `_canScrollToElement` at all.

**Comment by 117649** [comment]
This test branch have commits of other issue but most things seems working fine.
I think we are pretty much finished here.
https://github.com/117649/TabMixPlus/commit/357d754bc0a374ce7f273fbd860cc909bd7265b9

**Comment by onemen** [comment]
We need to update our gBrowser.tabContainer._positionPinnedTabs eval after [Bug 1696438](https://bugzilla.mozilla.org/show_bug.cgi?id=1696438) landed

**Review by 117649 — COMMENTED** [review]
> We need to update our gBrowser.tabContainer._positionPinnedTabs eval after [Bug 1696438](https://bugzilla.mozilla.org/show_bug.cgi?id=1696438) landed

It not so bad at least according to:https://hg.mozilla.org/mozilla-central/rev/660862625ba8#l1.12

I only see TMP use `layoutData.pinnedTabWidth`. What really changed is `layoutData.scrollButtonWidth`, which has been changed to `layoutData.scrollStartOffset`, but TMP did not messing with how it is calculated but just set it to 0 when needed. Thus it should be ok TMP just match the name change.
There hardly anything to change other then that. In fact, they even changed how `layoutData.pinnedTabWidth` is calculated to the same way of TMP.

And I would recommend warry about that after we merged this pr.

**Comment by 117649** [comment]
Do I need to try pack all changes into one commit?

**Comment by onemen** [comment]
> 
> 
> Do I need to try pack all changes into one commit?

NO

I will use squash and merge from github

**Comment by 117649** [comment]
`overflow-start-indicator` and `overflow-end-indicator` should be set to `display: none;` while multi-row is enabled.
`visibility: hidden;` is not enough, the border width still be counted. And that cause tab bar jumps when scrolling to top or bottom.

**Comment by onemen** [comment]
can you add a commit to address all your comments?

**Comment by 117649** [comment]
> can you add a commit to address all your comments?

Like everything in here?

**Comment by 117649** [comment]
> > can you add a commit to address all your comments?
> 
> Like everything in here?

This one is pretty much include everything I've talked about at here:
https://github.com/117649/TabMixPlus/commit/0c73b51ff8df753a09870dc33e516f2293ce4a6d

**Comment by onemen** [comment]
> This one is pretty much include everything I've talked about at here:
> [117649@0c73b51](https://github.com/117649/TabMixPlus/commit/0c73b51ff8df753a09870dc33e516f2293ce4a6d)

I will test how it work on my PC later this week

**Comment by 117649** [comment]
I've noticed several instances small pieces breaks, like scroll button disappear, non-scroll-able pinned tab not working .etc .
And we need a better scroll snap for multi-row.

**Comment by 117649** [comment]
Are we any close to a releasable version after this?

**Comment by 117649** [comment]
> 
> 
> When we finish this PR
> and
> #21, context menu issues: #34 #38
> i'v made some progress on these issues but u need to find the time ti finish the work

#34 & #38 are pretty straightforward, #21 and other problem related to DnD are tricky since that would involve multi-row thus better finish this PR first.

**Comment by onemen** [comment]
> i'v made some progress on these issues but u need to find the time ti finish the work

I need to find the time....

**Comment by 117649** [comment]
> 
> 
> > i'v made some progress on these issues but u need to find the time ti finish the work
> 
> I need to find the time....

I hope that will be soon.

Shits with proton is escalating fast.

**Comment by onemen** [comment]
There is an issue with multi-row and  **Tab width fits to tab title** preference.
When **Tab width fits to tab title** is off all the tab shrinks to the minimum width even on one row.
The reason for this is the code below. In the legacy Tabmix we use ```display: block``` for multi-row, now we use ```display: flex```.

```
/* :::: widthFitTitle :::: */
#tabbrowser-tabs[orient="horizontal"][widthFitTitle] > #tabbrowser-arrowscrollbox > .tabbrowser-tab:not([pinned]) {
  -moz-box-flex: 0 !important;
  width: auto !important;
}

#tabbrowser-tabs[orient="horizontal"]:not([widthFitTitle]) > #tabbrowser-arrowscrollbox > .tabbrowser-tab:not([pinned]):not([tiletabs-single="hidden"]) {
  -moz-box-flex: 100 !important;
  width: 0 !important;
}
```

**Comment by onemen** [comment]
Look like this work

```diff
#tabbrowser-tabs[orient="horizontal"]:not([widthFitTitle]) > #tabbrowser-arrowscrollbox > .tabbrowser-tab:not([pinned]):not([tiletabs-single="hidden"]) {
-   -moz-box-flex: 100 !important;
-   width: 0 !important;
+  flex: 1 1 auto;
}

```

**Comment by onemen** [comment]
Hi @117649 thank you for your help.

I think this is ready :)

try it to verify i did not miss any bug

**Comment by 117649** [comment]
图片
Drag in something and open a tab at most left of the tab bar just after fixed pinned tab cause spacing for fixed pinned tabs misplaced. 
图片
And that seems because spacing on first tab on current first row for pinned tabs is not updating.

I also recommend cherry pick 'bootstrap.js' part in this https://github.com/117649/TabMixPlus/commit/36527aebc1f1610be3f1bf6afaa0257efdad63ec.

**Comment by onemen** [comment]
> Drag in something and open a tab at most left of the tab bar just after fixed pinned tab cause spacing for fixed pinned tabs misplaced.
I will test if i can reproduce this issue, however it's maybe related to our drag&drop function that need BIG update.
maybe i push this PR and open new bug related to pinned tab ?

> I also recommend cherry pick 'bootstrap.js' part in this [117649@36527ae](https://github.com/117649/TabMixPlus/commit/36527aebc1f1610be3f1bf6afaa0257efdad63ec).

I'v used [onemen@94381b0](https://github.com/onemen/TabMixPlus/commit/94381b04844730f9cd64ef48eba94255ec0847ac)
and i don't see any issue with opening option dialog

**Comment by 117649** [comment]
> I will test if i can reproduce this issue, however it's maybe related to our drag&drop function that need BIG update.
> maybe i push this PR and open new bug related to pinned tab ?
No it not look like relate to DnD.  For what I can see now is because 'TabmixTabbar.singleRowHeight' giving out a whooping 93! which mess up the row calculate. Don't know why yet.

**Comment by 117649** [comment]
> I'v used [onemen@94381b0](https://github.com/onemen/TabMixPlus/commit/94381b04844730f9cd64ef48eba94255ec0847ac)
> and i don't see any issue with opening option dialog

 Open 'about:addons', open a lots of tabs, switch to 'about:addons', close browser, reopen browser and restore session, scroll  'about:addons' tab in tab bar out of view port, open TMP option.
And it focus tab bar on 'about:addons' and force scroll tab bar. Which it should not.

**Comment by 117649** [comment]
> 图片
> And that seems because spacing on first tab on current first row for pinned tabs is not updating.

For this something like this worked for me.
图片
```js
get singleRowHeight() {
    let heights = this._heights[this._tabsPosition];
    if (typeof (heights) == "undefined")
      return Tabmix.tabsUtils.scrollClientRect.height/this.visibleRows;
    return heights[2] / 2;
  },
```

**Comment by 117649** [comment]
> 图片
> Drag in something and open a tab at most left of the tab bar just after fixed pinned tab cause spacing for fixed pinned tabs misplaced.

And for this I think call `TabmixTabbar.setFirstTabInRow()` after a drop is enough.

**Comment by 117649** [comment]
Found there is several pixels height of loss space scroll-able while multi-tab is not overflowing under compact mode.

**Comment by onemen** [comment]
> 
> 
> Found there is several pixels height of loss space scroll-able while multi-tab is not overflowing under compact mode.

In which Firefox version?
can you post a screenshot?

**Comment by onemen** [comment]
> 
> 
> > I'v used [onemen@94381b0](https://github.com/onemen/TabMixPlus/commit/94381b04844730f9cd64ef48eba94255ec0847ac)
> > and i don't see any issue with opening option dialog
> 
> Open 'about:addons', open a lots of tabs, switch to 'about:addons', close browser, reopen browser and restore session, scroll 'about:addons' tab in tab bar out of view port, open TMP option.
> And it focus tab bar on 'about:addons' and force scroll tab bar. Which it should not.

> open TMP option
How do you open TMP option if 'about:addons' is out of view?

**Comment by onemen** [comment]
```js
get singleRowHeight() {
    let heights = this._heights[this._tabsPosition];
    if (typeof (heights) == "undefined")
      return Tabmix.tabsUtils.scrollClientRect.height/this.visibleRows;
    return heights[2] / 2;
  },
```
I'v missed that when i remove old code this._heights is no longer in use (also I haven't implemented tabs on bottom - that what tabsPosition is used for)

So at the moment ```if (typeof (heights) == "undefined")``` is always true. I the old days (Firefox 57) typeof (heights) was undefined only on single row!

The function should be
```js
get singleRowHeight() {
    return Tabmix.tabsUtils.scrollClientRect.height / this.visibleRows;
},
```
I will fix it soon :)

**Comment by 117649** [comment]
> 
> 
> > > I'v used [onemen@94381b0](https://github.com/onemen/TabMixPlus/commit/94381b04844730f9cd64ef48eba94255ec0847ac)
> > > and i don't see any issue with opening option dialog
> > 
> > 
> > Open 'about:addons', open a lots of tabs, switch to 'about:addons', close browser, reopen browser and restore session, scroll 'about:addons' tab in tab bar out of view port, open TMP option.
> > And it focus tab bar on 'about:addons' and force scroll tab bar. Which it should not.
> 
> > open TMP option
> 
> How do you open TMP option if 'about:addons' is out of view?

It is the selected tab. scroll tab in tab bar out of view.

图片
↓
图片
↓
图片
Notice the tab bar position has been pulled back.

**Comment by 117649** [comment]
> 
> 
> > Found there is several pixels height of loss space scroll-able while multi-tab is not overflowing under compact mode.
> 
> In which Firefox version?
> can you post a screenshot?

图片
图片
Notice the space between bottom row tabs and url bar.

**Comment by onemen** [comment]
> Notice the tab bar position has been pulled back.
> 
> It just this line:
> https://github.com/117649/TabMixPlus/blob/36527aebc1f1610be3f1bf6afaa0257efdad63ec/addon/bootstrap.js#L112
> It won't hurt.

The problem is that i can not reproduce the issue :(
Can you post a file with your Tab mix preference ?

> Found there is several pixels height of loss space scroll-able while multi-tab is not overflowing under compact mode.
>
> Notice the space between bottom row tabs and url bar.

i see., **new tab button** after tabs margin is to high. i'll fix this

**Comment by 117649** [comment]
> 
> 
> > Notice the tab bar position has been pulled back.
> > It just this line:
> > https://github.com/117649/TabMixPlus/blob/36527aebc1f1610be3f1bf6afaa0257efdad63ec/addon/bootstrap.js#L112
> > It won't hurt.
> 
> The problem is that i can not reproduce the issue :(
> Can you post a file with your Tab mix preference ?

eh, Have you close and restart Firefox with the 'about:addons' as the last selected tab?

Or you can try disable TMP in 'about:addons' refresh the 'about:addons' tab then enable TMP again. The result should be same.

This is something root in how our overlay system works. It is way before TMP preferences be read.
The reason is because when an extension is first load usually with browser startup the code we use load our overlay into every opened windows of the browser but after that we use the observer to load overlay into every "chrome-document". See the problem? 'about:addons' is a "chrome-document" but it is not a window it is a tab thus our overlay 'aboutaddons.xhtml' is not load into 'about:addons' that opened before extension start.

**Comment by onemen** [comment]
> Or you can try disable TMP in 'about:addons' refresh the 'about:addons' tab then enable TMP again. The result should be same.

That did it :)

its a race condition, that why it was difficult to reproduce, in my PC until the last test our code was always loaded in time.
I will add 
```
_win.gBrowser.tabs.filter(x=>x.linkedBrowser.currentURI.spec == 'about:addons' && x.linkedBrowser.contentWindow).forEach(x=>Overlays.load(chromeManifest, x.linkedBrowser.contentWindow));
```

**Comment by 117649** [comment]
> 
> 
> > Or you can try disable TMP in 'about:addons' refresh the 'about:addons' tab then enable TMP again. The result should be same.
> 
> That did it :)
> 
> its a race condition, that why it was difficult to reproduce, in my PC until the last test our code was always loaded in time.
> I will add
> 
> ```
> _win.gBrowser.tabs.filter(x=>x.linkedBrowser.currentURI.spec == 'about:addons' && x.linkedBrowser.contentWindow).forEach(x=>Overlays.load(chromeManifest, x.linkedBrowser.contentWindow));
> ```

I think it more a random thing depend on how your browser decide the loading sequence of extensions.

**Comment by onemen** [comment]
Thank you @117649  for your hard work and help

**Pull request merged**
