### PR TITLE
Fix: Auto reload may not always triggering if the tab is hidden

### LINKED ISSUE #121: Auto reload may not always triggering if the tab is hidden
@onemen Tab group extensions can put tabs in hidden state.
I also don't remember notice this ever happen before 98.
Maybe some thing related to some config?

And I found some thing a little annoying with attributes restore on tab restored. That is attributes is restored on tab finish loading but user can change the config before load is complete and that would be overwrite. And if the tab loading is timeout the attributes is not restored however if tab is refreshed the attributes is restored on next successful loading. But only timeout have this behavior other type of failed to load(e.g. 404) do not. 
Maybe not tie attribute restore to the restore state of individual tab?

### PR DESCRIPTION
**Pull request by onemen**
Attempt to fix #121 

@117649 , test if this patch fix the issue

### CODE REVIEW

**Comment by 117649** [comment]
I'll need to find time for this.
But I see "SSTabRestoring" is added to event list but it seems there is nothing to handle it?

By the way I'm using `Tabmix.restoreTabState(tab)` in `onSSWindowRestored` currently and nothing problematic so far.
```diff
   async onSSWindowRestored() {
    TMP_SessionStore.persistTabAttribute();
    // make sure we are fully initialized
    await Tabmix._deferredInitialized.promise;
    gBrowser.tabs.forEach(tab => {
      if (tab.hasAttribute("pending")) {
        const url = TabmixSvc.ss.getLazyTabValue(tab, "url");
        TMP_Places.asyncSetTabTitle(tab, url);
      }
+     Tabmix.restoreTabState(tab);
    });
```

**Comment by 117649** [comment]
@onemen I see no error msg in this so far.
But `SSTabRestored` is just not suit for this purpose it rely on network load.
We should replace it with call in `onSSWindowRestored`.

**Comment by onemen** [comment]
i can add also

```diff
async onSSWindowRestored() {
    TMP_SessionStore.persistTabAttribute();
    // make sure we are fully initialized
    await Tabmix._deferredInitialized.promise;
    gBrowser.tabs.forEach(tab => {
      if (tab.hasAttribute("pending")) {
        const url = TabmixSvc.ss.getLazyTabValue(tab, "url");
        TMP_Places.asyncSetTabTitle(tab, url);
      }
+     Tabmix.restoreTabState(tab);
    });
```

i want Tabmix.restoreTabState(tab) to be called as soon as possible, so I don't mind if it is triggered from SSTabRestored SSTabRestoring and SSWindowRestored

what do you think?

**Comment by 117649** [comment]
> i want Tabmix.restoreTabState(tab) to be called as soon as possible, so I don't mind if it is triggered from SSTabRestored SSTabRestoring and SSWindowRestored
> 
> what do you think?

The problem with `SSWindowRestored` as we've discussed before is it tied to network load which in particular is: if you have a connection issue and tab not loaded you then refresh it and it loaded the call is trigger at this time not when tab was stop loading due to connection failure.
This is not a behavior you can expect. You would not want that.

**Comment by onemen** [comment]
`Tabmix.restoreTabState(tab)` update Tabmix's related tab attribute that was restored by SessionStore
when SessionStore dispatch an event that indicate that something in the tab was change we want `Tabmix.restoreTabState(tab)` to update the tab. noticed that for auto-reload the relevant code only run on the first time that `"reload-data"` attribute exist on the tab. `if (reloadData && !aTab.hasAttribute("_reload"))`

**Comment by 117649** [comment]
I'm fearing there still edge cases it may affect like if for some reason user disabled auto-reload on a tab that is failed to connect. Would it been re-enabled upon a refresh?

**Pull request merged**
