### PR TITLE
This one should load I suppose.

### PR DESCRIPTION
**Pull request by 117649**
And just load overlay and option window into Firefox 78+ waterfox g3 included.

### CODE REVIEW

**Comment by onemen** [comment]
Thank you,
I will start working on this later this week.

**Comment by 117649** [comment]
There may be several extra fixes base on if I can get them work, stay tuned.

**Comment by 117649** [comment]
It's looks like some js module not want to load. Some how event listener on window load just not fire I have no idea of how this is happened, May be relate to something inside Overlay.jsm .

Other major problem is custom element not allow redefine element thus for tabbrowser-tab and scrollbox the changcode() is required to edit the class directly and/or have a watcher to edit every existent instance after they are created.

Sub tabs of prefpane is not working properly seems due to the module not load problem.

**Comment by 117649** [comment]
I think I'm hitting a stall here. The prefpane is load but tabbox and tabpanel inside it doesn't want to work. I can't figure out what cause it. It look no significant difference compare to those that function properly.

**Comment by 117649** [comment]
Peppering to try replace RDF services with RDFDataSource.jsm

reference
https://hg.mozilla.org/integration/mozilla-inbound/rev/f470abadfa78fc38e8ecd394bb893e1a1a4c71e3
https://hg.mozilla.org/integration/mozilla-inbound/rev/a2bc8b64659ae9e3387aa7b599aa38be773041e5

My take on this convert, standalone parts goes first leave those interact with browser inner to the last.

**Comment by onemen** [comment]
Any build instruction ?

I would link to move all file to sub directory src.
so i can add configuration files for lint tool an build tool in the root folder

**Comment by 117649** [comment]
I don't think I can give you any useful advice. I'm working on this by direct edit .xpi ...

**Comment by 117649** [comment]
maybe @xiaoxiaoflood knows better.

**Comment by xiaoxiaoflood** [comment]
I just pack everything in a zip, then rename to .xpi.

**Comment by 117649** [comment]
I think I'm kinda done all the easy to do part. What left a parts that tie into browser internal deeply and because of the changes browser have been through a lot of things just changed dramatically or no longer there like RDF.

So expect a long stall on the progress.

**Comment by onemen** [comment]
I will check how to implement this PR to the code.
I would like to add EsLint configuration, and some testing.

At the moment don't do any work on session manager (using RDF)
I'm plan to rewrite session manager from scratch. 

Please post future patch in separate PR

**Comment by 117649** [comment]
I'll do some clean up then try write a sum up.

**Comment by 117649** [comment]
1. The extension can be load into the browser with bootstrap helper but due to the eval() usage in the code you may need to disable csp for it to start running (partially).  Replace eval() with other method may be a better choice.
2. Preference window is mostly working and some of it options do have power like ones about context menu but most are not since the receiving part is missing.
3. I have implement a overlay and script for about:addon to open the pref window like the old one but after ff 81 the thing will cause the browser to crush. Refresh the page and wait for it to fully load do helps the situation through. I have no idea on how this is happen.
4. There are like 2 instances that TMP's replacement "warnAboutClosingTabs()" can not cover so I rename the TMP one and keep them separate. They seems working fine so far.
5. Mouse click preferences now only cause browser do unexpected behavior. And ctrl+click to select multiple tabs is now a default browser feature. 
6. Custom element not allow redefine a tag name so you can't override a element definition like xbl but we can still modify the original class object of the element. I'm plan on doing some experiments on this idea. 
7. Key key_tm_dupWin is complained missing but I can't find the thing in TMP' code.

That's all I can think about now.

**Pull request closed without merging**
