### PR TITLE
Create our buttons directly with CustomizableUI.createWidget

### PR DESCRIPTION
**Pull request by onemen**
While working on "Paste and Go" is broken issue #81, I have noticed that "Paste and Go" menu item is not visible, when one of our buttons is on "nav-bar" toolbar

After digging throw Firefox code and our code, the issue is as follows.

Firefox UrlbarInput class, aka gURLBar, insert "Paste and Go" menuitem dynamically into gURLBar input context menu. gURLBar installed by default in "nav-bar" toolbar.

Our code from Overlays.jsm runs after Firefox loaded, we insert our buttons its places by calling appendButton function.

In the process, the functions tempAppendAllToolbars and tempRestoreToolbar runs as well, and I think that those functions possibly trigger reset to some, if not all, dynamically added DOM nodes.

I have created this PR to fix this issue by adding our button widgets directly to CustomizableUI.
By doing so I have eliminate the need to use the code from Overlays.jsm.

@117649 can you check this PR.
What do you think?
Maybe we can remove some code from Overlays.jsm

### CODE REVIEW

**Comment by 117649** [comment]
I'm not sure if the problem is with **Overlays.jsm**, I hope not otherwise I have to update too **TabGroups** which isn't an easy job.

And I also remember saw this:
https://github.com/xiaoxiaoflood/firefox-scripts/issues/93#issuecomment-922429867

Same problem happens with just **userChromeJS**.
Hope this could help you locate the root cause.

**Comment by 117649** [comment]
@onemen I just install this PR.
I can confirm that "Paste and Go" is showing even after browser within 1 ~ 2 times which were all I have tested.
And I also not change any other setting or add-ons on my profile.
No problem so far.

**Comment by onemen** [comment]
@117649,

https://github.com/onemen/TabMixPlus/blob/fc8eca572d16fabbe560ec9466b9319db1b29654/addon/modules/bootstrap/Overlays.jsm#L726-L731

Line 727 do the damage.
when node is 'nav-bar', (nav-bar contains the gURLBar) before line 727 paste-and-go exist (check with ```aWindow.document.querySelector('[anonid=paste-and-go]')```), after that line it is missing.

I this we should remove that code and not use it since it can leads to unexpected side effect to Firefox and other extensions.

**Comment by 117649** [comment]
> I think we should remove that code and not use it since it can leads to unexpected side effect to Firefox and other extensions.

@onemen I don't know **TabGroups** should use same code but I haven't made any changes to it and everything is fine. May be it not calling that line. I think it could be a sequence of loading problem judge by how it was dealt with in **userChromeJS**: wait till gURLBar finish loading.

**Comment by onemen** [comment]
that line of code runs only when you add toolbarbutton to the nav-bar, and since our Overlays.jsm runs only after we get notified by `chrome-document-loaded` we sure gURLBar is loaded.

moving complete toolbar around ```node.tempAppend.container.appendChild(node);``` can lead to unexpected result !!!

**Comment by 117649** [comment]
> 
> 
> that line of code runs only when you add toolbarbutton to the nav-bar, and since our Overlays.jsm runs only after we get notified by `chrome-document-loaded` we sure gURLBar is loaded.
> 
> moving complete toolbar around `node.tempAppend.container.appendChild(node);` can lead to unexpected result !!!

@onemen I have some interesting finding. If I place **TabGroup** button in the nav-bar the problem will occur but if I put it in the tab bar it won't.
And get in get out customize mode can simply make "Paste and Go" reappear.
May be we could just call something after button append.

**Comment by onemen** [comment]
@117649 ,

I know!!

The issue with "Paste and Go" only appear when any button, from extensions that uses same Overlays.jsm, is on the `nav-bar` toolbar.

However you don't know if there any other hidden issues that are triggers by this approach. 
calling `UrlbarInput._initPasteAndGo` is just ignoring the danger in this code.

[Roomy Bookmarks](https://github.com/p1usminus/roomybookmarksredux/blob/master/src/bootstrap.js) use the same approach to load widgets

**Comment by 117649** [comment]
> 
> 
> @117649 ,
> 
> I know!!
> 
> The issue with "Paste and Go" only appear when any button, from extensions that uses same Overlays.jsm, is on the `nav-bar` toolbar.
> 
> However you don't know if there any other hidden issues that are triggers by this approach. calling `UrlbarInput._initPasteAndGo` is just ignoring the danger in this code.
> 
> [Roomy Bookmarks](https://github.com/p1usminus/roomybookmarksredux/blob/master/src/bootstrap.js) use the same approach to load widgets

@onemen  Call ```CustomizableUI.dispatchToolboxEvent("aftercustomization", {}, window);``` have the same result.
In fact Roomy Bookmarks get ride off using Overlays.jsm at all. I did that because there is just so little things need to be load it not really need that. But it a different story for **TabGroups** which have a backbone that load and unload everything all on the fly.

**Comment by onemen** [comment]
I'm planing to remove all the code from Overlays.jsm that handle "toolbarpalette" and CustomizableUI
we don't use it anymore

**Comment by 117649** [comment]
I've just comment out all tempAppendAllToolbars and tempRestoreToolbar uses in Overlays.jsm of TabGroup everything is fine.
All the remaining is CustomizableUI.createWidget calls.
No need to make a bunch of new files.

**Pull request merged**
